version: '2'

services:
  bft.node.0:
    container_name: bft.node.0
    hostname: bft.node.0
    image: bftsmart/fabric-orderingnode
    ports:
      - 11000:11000
      - 11001:11001
      - 11002:11002
      - 11003:11003
      - 11004:11004
      - 11100:11100
    working_dir: /etc/bftsmart-orderer
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    command: "0" 
    volumes:
      - /opt/gopath:/opt/gopath
      - ./config/node0config:/etc/bftsmart-orderer/config 
      - /var/run/:/host/var/run/
    extra_hosts:
      - "bft.node.1:10.255.71.38"
      - "bft.node.2:10.255.73.122"
      - "bft.node.3:10.255.73.123"
