FROM bftsmart/fabric-common:x86_64-1.1.1

WORKDIR /etc/bftsmart-orderer/

RUN echo "#!/bin/bash" > reconfigure.sh
RUN echo "java -cp bin/orderingservice.jar:lib/* bft.util.FabricVMServices \$@" >> reconfigure.sh

RUN chmod +x ./reconfigure.sh

ENTRYPOINT ["./reconfigure.sh"]
CMD [""]
