FROM bftsmart/fabric-frontend:x86_64-1.1.1

WORKDIR /etc/bftsmart-orderer/

RUN echo "#!/bin/bash" > startWorkload.sh
RUN echo "java -DWORKLOAD_CLIENT_ID=\$1 -cp bin/orderingservice.jar:lib/* bft.test.WorkloadClient \$@" >> startWorkload.sh

RUN chmod +x ./startWorkload.sh

ENTRYPOINT ["./startWorkload.sh"]
CMD [""]
