FROM bftsmart/fabric-common:x86_64-1.1.1

ADD ./temp/sampleconfig/msp/signcerts/peer.pem /etc/bftsmart-orderer/config/cert.pem
ADD ./temp/sampleconfig/msp/keystore/key.pem /etc/bftsmart-orderer/config/key.pem

RUN apt-get autoremove -y
RUN apt-get clean -y

WORKDIR /etc/bftsmart-orderer/

RUN echo "#!/bin/bash" > startReplica.sh
RUN echo "java -DNODE_ID=\$1 -cp bin/orderingservice.jar:lib/* bft.BFTNode \$@" >> startReplica.sh

RUN chmod +x ./startReplica.sh

ENTRYPOINT ["./startReplica.sh"]
CMD [""]
