NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.cli.bft-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.cli.bft-cert.pem
    OrganizationalUnitIdentifier: peer
