# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrganizationalUnitIdentifiers:
  - Certificate: "cacerts/cacert.pem"
    OrganizationalUnitIdentifier: "COP"

NodeOUs:
  Enable: false
  ClientOUIdentifier:
    # if Certificate is empty, then the certifier identifier will not be enforced
    Certificate: "cacerts/cacert.pem"
    OrganizationalUnitIdentifier: "OU_client"
  PeerOUIdentifier:
    Certificate: "cacerts/cacert.pem"
    OrganizationalUnitIdentifier: "OU_peer"
